<a href="https://colab.research.google.com/github/i2mmmmm/Study/blob/main/Google_ML_Bootcamp/Coursera/1.2%20Deep%20Neural%20Networks4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Broadcasting example
- [1,2,3,4] + 100 이렇게 쓰면 Python에서는 알아서 100을 [100,100,100,100]으로 **자동 확장**한다.

- [1 2 3] + [100 200 300]　->　[1 2 3] + [100 200 300]  
  [4 5 6]　　　　　　　　　　[4 5 6]　[100 200 300]

- (m,n) + (1,n) 행렬 더할 때도 (1,n) 행렬을 m번 복사하여 **자동으로 (m,n)으로** 바꾼다.
- 마찬가지로 (m,n) + (m,1) 행렬을 더할 때에도 (m,1) 행렬을 n번 복사하여 **자동으로 (m,n)으로** 바꾼다.

In [3]:
import numpy as np

A = np.array([[56,0,4.4,68],
             [1.2,104,52,8],
             [1.8,135,99,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [11]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [14]:
per = 100*A/cal
print(per)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


### 버그를 만들지 않는 팁!

- **1순위 배열** (rank 1 arrays) 을 사용하지 않는 것.
- a.shape = (5,) 이라면 a = a.**reshape**(5,1) 해서 rank-1 배열을 없애는 것이 좋다.

In [16]:
a = np.random.randn(5) # <1순위 배열> 이라고 함
print(a)              # 이것을 사용하지 않는 것을 추천
# -> (5,1) or (1,5)로 만들어서 일관된 행동을 하게끔 해야함
# -> a = a.reshape(5,1) 1순위 배열은 이렇게 변형하기

[-0.67455937  0.02682557 -2.42564468 -0.67657165  2.15719521]


In [21]:
print(a.shape)
print(a.T)
print((a.T).shape)

(5,)
[-0.67455937  0.02682557 -2.42564468 -0.67657165  2.15719521]
(5,)


In [24]:
print(np.dot(a,a.T))
print(np.dot(a.T,a))

11.450742408678103
11.450742408678103


In [22]:
b = np.random.randn(5,1)
print(b)

[[-0.48334621]
 [-1.35346001]
 [-1.6436072 ]
 [ 0.78370974]
 [ 1.23504239]]


In [23]:
print(b.T)
print(b.shape)
print(b.T.shape)
#a, b 차이점 [[ 대괄호 두 개 ]]

[[-0.48334621 -1.35346001 -1.6436072   0.78370974  1.23504239]]
(5, 1)
(1, 5)


In [25]:
print(np.dot(b,b.T))
print(np.dot(b.T,b))

[[ 0.23362356  0.65418976  0.79443131 -0.37880313 -0.59695306]
 [ 0.65418976  1.83185399  2.22455662 -1.0607198  -1.67158049]
 [ 0.79443131  2.22455662  2.70144463 -1.28811098 -2.02992457]
 [-0.37880313 -1.0607198  -1.28811098  0.61420096  0.96791476]
 [-0.59695306 -1.67158049 -2.02992457  0.96791476  1.52532971]]
[[6.90645286]]
