<a href="https://colab.research.google.com/github/i2mmmmm/Study/blob/main/Python/basic/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. 벡터화 연산(Vectorized Operations)  
NumPy는 벡터화 연산을 지원.  
벡터화 연산은 반복문 없이 전체 배열에 대해 수치 연산을 수행하는 방식으로, 일반적인 파이썬 루프보다 훨씬 빠르게 동작한다.  
이는 NumPy가 내부적으로 C로 구현되어 있어, 저수준 최적화를 통해 연산 속도를 극대화하기 때문이다.

In [ ]:
import time

# 일반 파이썬 리스트
arr = list(range(1000000))

start_time = time.time()
arr = [x * 2 for x in arr]
end_time = time.time()

print("일반 파이썬 리스트 시간:", end_time - start_time)

일반 파이썬 리스트 시간: 0.16766047477722168


In [ ]:
import numpy as np

# NumPy 배열
arr = np.arange(1000000)

start_time = time.time()
arr = arr * 2
end_time = time.time()

print("NumPy 배열 시간:", end_time - start_time)

NumPy 배열 시간: 0.011507749557495117


## 2. 효율적인 메모리 사용
NumPy는 배열을 위한 고정된 타입의 메모리 블록을 사용.  
이는 파이썬의 리스트와 달리 메모리 사용이 훨씬 효율적이며, 메모리 캐시 친화적이다.

## 3. 다양한 기능과 최적화
NumPy는 수많은 내장 함수와 최적화된 루틴을 제공하여 복잡한 수치 연산을 쉽게 수행할 수 있게 해준다.  
이는 시간 복잡도를 줄이고 코드의 간결성과 가독성을 높이는 데 큰 도움이 된다.


In [ ]:
# 일반 파이썬 리스트
a = list(range(1000000))
b = list(range(1000000))

start_time = time.time()
c = [a[i] + b[i] for i in range(len(a))]
end_time = time.time()

print("일반 파이썬 리스트 시간:", end_time - start_time)

일반 파이썬 리스트 시간: 0.17985749244689941


In [ ]:
# NumPy 배열
a = np.arange(1000000)
b = np.arange(1000000)

start_time = time.time()
c = a + b
end_time = time.time()

print("NumPy 배열 시간:", end_time - start_time)

NumPy 배열 시간: 0.005232334136962891


시간으로 확인할 수 있듯이 NumPy는 특히 대규모 데이터 처리 및 수치 연산에 있어 매우 효율적이다.  
벡터화 연산, 효율적인 메모리 사용, 최적화된 내장 함수 등을 통해 시간 복잡도와 성능을 크게 개선할 수 있다.  
따라서 수치 연산이 많이 필요한 작업에서는 NumPy를 사용하는 것이 좋다.

### 예제 1. 배열 생성

In [16]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6]])

In [2]:
zeros = np.zeros((3, 3))    # 0으로 채워진
ones = np.ones((3, 3))      # 1로 채워진
full = np.full((3, 3), 7)   # 7로 채워진

In [5]:
print(full)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [7]:
arange = np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]   # 연속된 값이나 특정 간격으로 배열
linspace = np.linspace(0, 1, 5)  # [0. , 0.25, 0.5 , 0.75, 1. ]

In [12]:
random_array = np.random.rand(3, 3)             # 랜덤으로
random_int = np.random.randint(0, 10, (3, 3))   # 랜덤 (정수)
random_number = np.random.randn(3, 3)           # 표준 정규 분포를 따르는 난수를 생성

In [13]:
random_number

array([[ 1.38402969,  1.16363986, -0.49604596],
       [-0.62804106, -1.54623833,  0.37452914],
       [ 1.63245402, -0.1950604 ,  0.84079053]])

### 예제 2. 배열 조작

In [14]:
# 배열 모양 변경

reshaped = np.reshape(b, (3, 2))  #array([[1, 2],
                                  #       [3, 4],
                                  #       [5, 6]])
flattened = b.flatten()           # array([1, 2, 3, 4, 5, 6])

In [22]:
# 슬라이싱, 인덱싱

sub_array = b[0, 1]  # 2
row = b[0, :]  # [1, 2, 3]
column = b[:, 1]  # [2, 5]

In [23]:
# 배열 결합 / 분할

# a = array([1, 2, 3])
vstacked = np.vstack((a, a))  # array([[1, 2, 3],
                              #        [1, 2, 3]])
hstacked = np.hstack((a, a))  # array([1, 2, 3, 1, 2, 3])
split = np.split(a, 3)        # [array([1]), array([2]), array([3])]

### 예제 3. 배열 연산

In [32]:
c = a + 1               # [2, 3, 4]
d = b * 2               # [[2, 4, 6], [8, 10, 12]]
e = np.add(a, a)        # [2, 4, 6]
f = np.multiply(b, 2)   # [[2, 4, 6], [8, 10, 12]]

In [33]:
dot_product = np.dot(a, a)  # 14 (1*1 + 2*2 + 3*3)
matrix_multiplication = np.matmul(b, b.T)   # array([[14, 32],
                                            #        [32, 77]])

In [36]:
broadcast = a + np.array([1, 2, 3])  # [2, 4, 6]

In [37]:
mean = np.mean(a)   # 2.0
sum = np.sum(a)     # 6
std = np.std(a)     # 0.816496580927726

In [38]:
max_val = np.max(a)  # 3
min_val = np.min(a)  # 1
argmax = np.argmax(a)  # 2
argmin = np.argmin(a)  # 0

### 예제 4. 함수

In [40]:
# 배열 복사

copied_array = np.copy(a)
print(copied_array)

[1 2 3]


In [41]:
condition = a > 1
filtered_array = a[condition]  # [2, 3]

In [42]:
unique_vals = np.unique(a)  # [1, 2, 3]